<%
foreach (BaseTreeNode entityNode in Model.Children) {
    EntityNode currentEntity = (EntityNode)entityNode;
    if (currentEntity.GenerateObject && (currentEntity.PrimaryKeyFields.Count != 0 || currentEntity.GenerateAsReadOnly)) {%>
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version <%Response.Write(parameters["GeneratorVersion"]);%>
// Created: <%Response.Write(DateTime.Today.ToShortDateString());%> - <%Response.Write(DateTime.Now.ToShortTimeString());%>
// This is a partial class file. The other one is <%Response.Write(currentEntity.GenerateAs);%>Mapper.Auto.cs
// You can edit this file as your wish.
//------------------------------------------------------------------------------

using <%Response.Write(parameters["RulesProjectName"]);%>.Objects<%Response.Write(currentEntity.FormattedNamespace);%>;
using <%Response.Write(parameters["RulesProjectName"]);%>.Entities;
using Cooperator.Framework.Core;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using System.Data.Common;
using System.Reflection;
using System;

namespace <%Response.Write(parameters["RulesProjectName"]);%>.Mappers<%Response.Write(currentEntity.FormattedNamespace);%>
{

    /// <summary>
    /// Mapper for <%Response.Write(currentEntity.GenerateAs);%> entity
    /// This class provide persistence methods for this entity
    /// </summary>
    public  partial class <%Response.Write(currentEntity.GenerateAs);%>Mapper
    {
        // /// <summary>
        // /// Enables GetObjectBySQLText and GetObjectListBySQLText methods.
        // /// </summary>
        //protected override bool SQLQueriesEnabled()
        //{
        //    return true;
        //}

        // /// <summary>
        // /// Checks for security ritghs
        // /// </summary>
        //protected override bool CheckForSecurityRights(SecurityRights action, <%Response.Write(currentEntity.GenerateAs);%>List ObjectListOrEntityList)
        //{
        //    switch (action)
        //    {
        //        case SecurityRights.Read:
        //            return true;
        //        case SecurityRights.Insert:
        //            return true;
        //        case SecurityRights.Update:
        //            return true;
        //        case SecurityRights.Delete:
        //            return true;
        //    }
        //    return false;
        //}

    }

}


namespace <%Response.Write(parameters["RulesProjectName"]);%>.Loaders<%Response.Write(currentEntity.FormattedNamespace);%>
{

    /// <summary>
    /// Loader for <%Response.Write(currentEntity.GenerateAs);%> entity
    /// This class provide get methods for this entity
    /// </summary>
    public partial class <%Response.Write(currentEntity.GenerateAs);%>Loader
    {
    }

}


<%
Response.SaveBuffer("\\Mappers\\" + currentEntity.FullGenerateAs + "Mapper.cs");
}
}
%>
