<%EntityNode currentEntity = (EntityNode) Model.Children[0];%>
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version <%Response.Write(parameters["GeneratorVersion"]);%>
// Created: <%Response.Write(DateTime.Today.ToShortDateString());%> - <%Response.Write(DateTime.Now.ToShortTimeString());%>
// You can edit this file as your wish.
//------------------------------------------------------------------------------

using <%Response.Write(parameters["RulesProjectName"]);%>.Entities;
using <%Response.Write(parameters["RulesProjectName"]);%>.Objects;
using <%Response.Write(parameters["RulesProjectName"]);%>.Mappers;
using System.Data.Common;
using System;

public class RuleExample: Cooperator.Framework.Data.BaseRule
{

    public static void DoSomething()
    {

        //Start transaction
        DbTransaction tr = (new RuleExample()).DataBaseHelper.GetAndBeginTransaction();
        DbConnection conn = tr.Connection;

        try {
            //Create entity
            Entity1 myObj1 = new Entity1(1, "1000101");

            //Insert myObj1 in transaction
            Entity1Mapper.Instance().Insert(tr, myObj1);

            //Create another entity
            Entity2 myObj2 = new Entity2(22);

            //Delete myObj2 in transaction
            Entity2Mapper.Instance().Delete(tr, myObj2);

            //Commit transaction
            tr.Commit();

        }
        catch (Exception ex) {

            //If an error occur, rollback the transaction
            tr.Rollback();

            //Throw the original error
            throw;
        }
        finally
        {
            conn.Close();
            tr.Dispose();
        }

    }
}

<%
Response.SaveBuffer("\\Rules\\RuleExample.cs");
%>
