<%
foreach (BaseTreeNode entityNode in Model.Children) {
    EntityNode currentEntity = (EntityNode)entityNode;
    if (currentEntity.GenerateEntity && currentEntity.GenerateObject && (currentEntity.PrimaryKeyFields.Count != 0 || currentEntity.GenerateAsReadOnly)) {%>
'------------------------------------------------------------------------------
' This file was generated by Cooperator Modeler, version <%Response.Write(parameters["GeneratorVersion"]);%>
' Created: <%Response.Write(DateTime.Today.ToShortDateString());%> - <%Response.Write(DateTime.Now.ToShortTimeString());%>
' This is a partial class file. The other one is <%Response.Write(currentEntity.GenerateAs);%>Entity.Auto.cs
' You can edit this file as your wish.
'------------------------------------------------------------------------------

Imports System
Imports Cooperator.Framework.Core.Exceptions

Namespace Entities<%Response.Write(currentEntity.FormattedNamespace);%>
    ''' <summary>
    ''' This class represents the <%Response.Write(currentEntity.GenerateAs);%> entity.
    ''' </summary>
    ''' <remarks></remarks>
    <Serializable> _
    Public Partial Class <%Response.Write(currentEntity.GenerateAs);%>
        ' Implements IValidable

        ' ''' <summary>
        ' ''' When IValidable is implemented, this method is invoked by Gateway before Insert or Update to validate Object.
        ' ''' </summary>
        ' ''' <remarks></remarks>
        ' Public Sub Validate()
        '     'Example:
        '     If String.IsNullOrEmpty(me.Name) Then Throw New RuleValidationException("Name can't be null")
        ' End Sub
    End Class

    ''' <summary>
    ''' This class represents a collection of <%Response.Write(currentEntity.GenerateAs);%> entity.
    ''' </summary>
    Public Partial Class <%Response.Write(currentEntity.GenerateAs);%>List
         ' ''' <summary>
         ' ''' Returns a typed Dataset based on its content.
         ' ''' </summary>
         'Public Overrides Function ToDataSet() As System.Data.DataSet
         '    YOUR_TYPED_DATASET MyDataSet = new YOUR_TYPED_DATASET();
         '    ObjectListHelper<<%Response.Write(currentEntity.GenerateAs);%>, <%Response.Write(currentEntity.GenerateAs);%>List> Exporter = new ObjectListHelper<<%Response.Write(currentEntity.GenerateAs);%>, <%Response.Write(currentEntity.GenerateAs);%>List>();
         '    Exporter.FillDataSet(MyDataSet, this)
         '    Return MyDataSet
         'End Function
    End Class


End Namespace

Namespace Views<%Response.Write(currentEntity.FormattedNamespace);%>
    ''' <summary>
    ''' This class represents a view of an collection of <%Response.Write(currentEntity.Name);%> entities.
    ''' </summary>
    Partial Public Class <%Response.Write(currentEntity.GenerateAs);%>ListView
    End Class
End Namespace

<%
Response.SaveBuffer("\\Entities\\" + currentEntity.FullGenerateAs + ".vb");
}
}
%>
