<%
foreach (BaseTreeNode entityNode in Model.Children) {
    EntityNode currentEntity = (EntityNode)entityNode;
    if (currentEntity.GenerateObject && (currentEntity.PrimaryKeyFields.Count != 0 || currentEntity.GenerateAsReadOnly)) {%>
'------------------------------------------------------------------------------
' This file was generated by Cooperator Modeler, version <%Response.Write(parameters["GeneratorVersion"]);%>
' Created: <%Response.Write(DateTime.Today.ToShortDateString());%> - <%Response.Write(DateTime.Now.ToShortTimeString());%>
' This is a partial class file. The other one is <%Response.Write(currentEntity.GenerateAs);%>Gateway.Auto.vb
' You can edit this file as your wish.
'------------------------------------------------------------------------------

Imports <%Response.Write(parameters["RulesProjectName"]);%>.Objects<%Response.Write(currentEntity.FormattedNamespace);%>
Imports Cooperator.Framework.Core
Imports Cooperator.Framework.Data
Imports Cooperator.Framework.Data.Exceptions
Imports System.Data.Common
Imports System.Reflection
Imports System

Namespace Gateways<%Response.Write(currentEntity.FormattedNamespace);%>

    ''' <summary>
    ''' Gateway between <%Response.Write(currentEntity.GenerateAs);%>Object class and <%Response.Write(currentEntity.Name);%> table.
    ''' This class provide CRUD methods for <%Response.Write(currentEntity.Name);%> table.
    ''' </summary>
    Public Partial Class <%Response.Write(currentEntity.GenerateAs);%>Gateway

        ' ''' <summary>
        ' ''' Enables GetObjectBySQLText and GetObjectListBySQLText methods.
        ' ''' </summary>
        'Protected Overrides Function SQLQueriesEnabled() As Boolean
        '    Return True
        'End Function

        ' ''' <summary>
        ' ''' Checks for security ritghs
        ' ''' </summary>
        'Protected Overrides Function CheckForSecurityRights(ByVal action As SecurityRights, ByVal ObjectListOrEntityList As <%Response.Write(currentEntity.GenerateAs);%>ObjectList) As Boolean
        '    Select Case action
        '        Case SecurityRights.Read
        '            Return True
        '        Case SecurityRights.Insert
        '            Return True
        '        Case SecurityRights.Update
        '            Return True
        '        Case SecurityRights.Delete
        '            Return True
        '    End Select
        'End Function

    End Class

End Namespace


<%
Response.SaveBuffer("\\Gateways\\" + currentEntity.FullGenerateAs + "Gateway.vb");
}
}
%>
