<%
foreach (BaseTreeNode entityNode in Model.Children) {
    EntityNode currentEntity = (EntityNode)entityNode;
    if (currentEntity.GenerateObject && (currentEntity.PrimaryKeyFields.Count != 0 || currentEntity.GenerateAsReadOnly)) {%>
'------------------------------------------------------------------------------
' This file was generated by Cooperator Modeler, version <%Response.Write(parameters["GeneratorVersion"]);%>
' Created: <%Response.Write(DateTime.Today.ToShortDateString());%> - <%Response.Write(DateTime.Now.ToShortTimeString());%>
' This is a partial class file. The other one is <%Response.Write(currentEntity.GenerateAs);%>Mapper.Auto.cs
' You can edit this file as your wish.
'------------------------------------------------------------------------------

Imports <%Response.Write(parameters["RulesProjectName"]);%>.Objects<%Response.Write(currentEntity.FormattedNamespace);%>
Imports <%Response.Write(parameters["RulesProjectName"]);%>.Entities
Imports Cooperator.Framework.Core
Imports Cooperator.Framework.Data
Imports Cooperator.Framework.Data.Exceptions
Imports System.Data.Common
Imports System.Reflection
Imports System

Namespace Mappers<%Response.Write(currentEntity.FormattedNamespace);%>

    ''' <summary>
    ''' Mapper for <%Response.Write(currentEntity.GenerateAs);%> entity
    ''' This class provide persistence methods for this entity
    ''' </summary>
    Public Partial Class <%Response.Write(currentEntity.GenerateAs);%>Mapper

        ' ''' <summary>
        ' ''' Enables GetObjectBySQLText and GetObjectListBySQLText methods.
        ' ''' </summary>
        'Protected Overrides Function SQLQueriesEnabled() As Boolean
        '    Return True
        'End Function

        ' ''' <summary>
        ' ''' Checks for security ritghs
        ' ''' </summary>
        'Protected Overrides Function CheckForSecurityRights(ByVal action As SecurityRights, ByVal ObjectListOrEntityList As <%Response.Write(currentEntity.FullGenerateAs);%>List) As Boolean
        '    Select Case action
        '        Case SecurityRights.Read
        '            Return True
        '        Case SecurityRights.Insert
        '            Return True
        '        Case SecurityRights.Update
        '            Return True
        '        Case SecurityRights.Delete
        '            Return True
        '    End Select
        'End Function

    End Class
End Namespace

Namespace Loaders<%Response.Write(currentEntity.FormattedNamespace);%>

    ''' <summary>
    ''' Loader for <%Response.Write(currentEntity.GenerateAs);%> entity
    ''' This class provide get methods for this entity
    ''' </summary>
    Public Partial Class <%Response.Write(currentEntity.GenerateAs);%>Loader
    End Class

End Namespace


<%
Response.SaveBuffer("\\Mappers\\" + currentEntity.FullGenerateAs + "Mapper.vb");
}
}
%>
