<%EntityNode currentEntity = (EntityNode) Model.Children[0];%>
'------------------------------------------------------------------------------
' This file was generated by Cooperator Modeler, version <%Response.Write(parameters["GeneratorVersion"]);%>
' Created: <%Response.Write(DateTime.Today.ToShortDateString());%> - <%Response.Write(DateTime.Now.ToShortTimeString());%>
' You can edit this file as your wish.
'------------------------------------------------------------------------------

Imports <%Response.Write(parameters["RulesProjectName"]);%>.Entities
Imports <%Response.Write(parameters["RulesProjectName"]);%>.Objects
Imports <%Response.Write(parameters["RulesProjectName"]);%>.Mappers
Imports System.Data.Common

Public Class RuleExample
    Inherits Cooperator.Framework.Data.BaseRule

    Public Shared Sub DoSomething()

        'Start transaction
        Dim tr As DbTransaction = (New RuleExample()).DataBaseHelper.GetAndBeginTransaction()
        Dim conn As DbConnection = tr.Connection

        Try
            'Create entity
            Dim myObj1 As Entity1 = New Entity1(1, "1000101")

            'Insert myObj1 in transaction
            Entity1Mapper.Instance().Insert(tr, myObj1)

            'Create another entity
            Dim myObj2 As Entity2 = New Entity2(22)

            'Delete myObj2 in transaction
            Entity2Mapper.Instance().Delete(tr, myObj2)

            'Commit transaction
            tr.Commit()

        Catch ex As Exception

            'If an error occur, rollback the transaction
            tr.Rollback()

            'Throw the original error
            Throw

        Finally
            conn.Close()
            tr.Dispose()
        End Try

    End Sub

End Class

<%
Response.SaveBuffer("\\Rules\\RuleExample.vb");
%>

